export const SIM_URL = '/sim-product'
export const WIFI_URL = '/wifi-product'
export const IMAGE_URL = '/image'
export const LIST_POSTS_URL = '/list-posts'
export const POST_URL = '/post'
export const ORDER_URL = '/order'
